#!/usr/bin/env bash
set -Eeuo pipefail

# ===========================
#  Proxy Squid Installer v2
#  - Fix unbound variables
#  - Interactive + args mode
#  - Telegram optional
#  - Self-update from GitHub raw
# ===========================

SCRIPT_NAME="creatproxy.sh"
SQUID_CONF="/etc/squid/squid.conf"
SQUID_PASSWD="/etc/squid/passwd"
SQUID_LOG="/var/log/squid/access.log"

# --- CHANGE THIS to your GitHub RAW (direct file) ---
# Example:
# UPDATE_URL="https://raw.githubusercontent.com/<user>/<repo>/main/creatproxy.sh"
UPDATE_URL="${UPDATE_URL:-https://raw.githubusercontent.com/letanluc310300/taoproxy/refs/heads/main/creatproxy.sh}"

# Telegram (optional)
BOT_TOKEN="$7737030927:AAEmdQNSxxKE7HgnhyOAORuqoRYMFcPnWGc"
CHAT_ID="$6267128183"

log()  { echo -e "[$(date +'%F %T')] $*"; }
die()  { echo -e "❌ $*" >&2; exit 1; }

need_root() {
  [[ "${EUID:-$(id -u)}" -eq 0 ]] || die "Hãy chạy bằng root. Ví dụ: sudo bash $SCRIPT_NAME"
}

detect_pkg_mgr() {
  if command -v apt >/dev/null 2>&1; then
    echo "apt"
  elif command -v yum >/dev/null 2>&1; then
    echo "yum"
  elif command -v dnf >/dev/null 2>&1; then
    echo "dnf"
  else
    die "Không tìm thấy apt/yum/dnf."
  fi
}

install_deps() {
  local pm
  pm="$(detect_pkg_mgr)"
  log "➡️  Installing dependencies (squid, apache2-utils/htpasswd, curl)..."

  case "$pm" in
    apt)
      export DEBIAN_FRONTEND=noninteractive
      apt update -y
      apt install -y squid apache2-utils curl
      ;;
    yum)
      yum install -y squid httpd-tools curl
      ;;
    dnf)
      dnf install -y squid httpd-tools curl
      ;;
  esac
}

random_port() {
  # 2000-65000
  echo $(( (RANDOM % 63000) + 2000 ))
}

get_public_ip() {
  # ưu tiên IPv4
  curl -s -4 ifconfig.me 2>/dev/null || true
}

ensure_htpasswd() {
  command -v htpasswd >/dev/null 2>&1 || die "Thiếu htpasswd. Hãy cài apache2-utils/httpd-tools."
}

write_squid_conf() {
  local port="$1"
  cp -f "$SQUID_CONF" "${SQUID_CONF}.bak.$(date +%s)" 2>/dev/null || true

  cat > "$SQUID_CONF" <<EOF
# Generated by Proxy Squid Installer v2
auth_param basic program /usr/lib/squid/basic_ncsa_auth $SQUID_PASSWD
auth_param basic realm ProxyKing
acl authenticated proxy_auth REQUIRED
http_access allow authenticated
http_port $port

cache deny all
access_log $SQUID_LOG
EOF
}

restart_squid() {
  systemctl enable squid >/dev/null 2>&1 || true
  systemctl restart squid
  systemctl --no-pager --full status squid | sed -n '1,10p' || true
}

send_telegram() {
  local msg="$1"
  # Nếu chưa set token/chat_id thì bỏ qua
  if [[ "$BOT_TOKEN" == "YOUR_BOT_TOKEN" || "$CHAT_ID" == "YOUR_CHAT_ID" ]]; then
    log "ℹ️  Telegram chưa cấu hình BOT_TOKEN/CHAT_ID nên bỏ qua gửi."
    return 0
  fi

  curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
    -d chat_id="$CHAT_ID" \
    --data-urlencode text="$msg" >/dev/null || true
}

add_user() {
  local username="$1"
  local password="$2"
  ensure_htpasswd
  htpasswd -bc "$SQUID_PASSWD" "$username" "$password" >/dev/null
}

show_info() {
  local ip port
  ip="$(get_public_ip)"
  if [[ -f "$SQUID_CONF" ]]; then
    port="$(grep -E '^http_port ' "$SQUID_CONF" | awk '{print $2}' | head -n1 || true)"
  else
    port=""
  fi

  echo "===================================="
  echo "🧾 Squid config: $SQUID_CONF"
  echo "👤 Passwd file : $SQUID_PASSWD"
  echo "📄 Log         : $SQUID_LOG"
  echo "🌐 Public IPv4 : ${ip:-"(không lấy được)"}"
  echo "🔌 Port        : ${port:-"(chưa cấu hình)"}"
  echo "===================================="
}

uninstall_all() {
  local pm
  pm="$(detect_pkg_mgr)"
  log "⚠️  Uninstall squid & remove config..."
  systemctl stop squid >/dev/null 2>&1 || true

  rm -f "$SQUID_PASSWD" || true
  rm -f "$SQUID_CONF" || true

  case "$pm" in
    apt) apt remove -y squid apache2-utils || true ;;
    yum) yum remove -y squid httpd-tools || true ;;
    dnf) dnf remove -y squid httpd-tools || true ;;
  esac

  log "✅ Done uninstall."
}

self_update() {
  need_root
  log "⬇️  Updating script from: $UPDATE_URL"
  local tmp="/tmp/${SCRIPT_NAME}.$RANDOM"
  curl -fsSL "$UPDATE_URL" -o "$tmp" || die "Không tải được UPDATE_URL (check link raw)."
  chmod +x "$tmp"

  # Replace current script if possible
  if [[ -w "$0" ]]; then
    cp -f "$tmp" "$0"
    chmod +x "$0"
    log "✅ Updated in-place: $0"
  else
    # fallback install to /usr/local/bin
    cp -f "$tmp" "/usr/local/bin/$SCRIPT_NAME"
    chmod +x "/usr/local/bin/$SCRIPT_NAME"
    log "✅ Installed updated script to: /usr/local/bin/$SCRIPT_NAME"
    log "👉 Lần sau chạy: sudo $SCRIPT_NAME ..."
  fi
}

usage() {
  cat <<'EOF'
Usage:
  sudo bash creatproxy.sh [command] [options]

Commands:
  install         Cài squid + tạo user + cấu hình port
  adduser         Thêm user/password (không đổi port)
  show            Xem thông tin cấu hình
  uninstall       Gỡ squid + xóa config
  update          Tự cập nhật script từ GitHub raw

Options (for install/adduser):
  --user USER
  --pass PASS
  --port PORT
  --send-tele y|n

Examples:
  sudo bash creatproxy.sh install --user abc --pass 123 --port 3128 --send-tele y
  sudo bash creatproxy.sh adduser --user abc --pass 123
  sudo bash creatproxy.sh update

EOF
}

# --- parse args safely ---
CMD="${1:-}"
shift || true

USER_ARG=""
PASS_ARG=""
PORT_ARG=""
SEND_TELE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --user) USER_ARG="${2:-}"; shift 2 || true ;;
    --pass) PASS_ARG="${2:-}"; shift 2 || true ;;
    --port) PORT_ARG="${2:-}"; shift 2 || true ;;
    --send-tele) SEND_TELE="${2:-}"; shift 2 || true ;;
    -h|--help) usage; exit 0 ;;
    *) die "Tham số không hợp lệ: $1 (dùng --help)" ;;
  esac
done

interactive_install() {
  local username password port send_tele ip
  read -rp "Bạn muốn nhập username? (y/n): " choice || true
  if [[ "${choice:-n}" =~ ^[yY]$ ]]; then
    read -rp "Nhập username: " username
    password="$(tr -dc A-Za-z0-9 </dev/urandom | head -c 10)"
  else
    username="kingproxy"
    password="kingproxy"
  fi

  read -rp "Bạn muốn chọn port? (y/n): " pchoice || true
  if [[ "${pchoice:-n}" =~ ^[yY]$ ]]; then
    read -rp "Nhập port (1-65535): " port
  else
    port="$(random_port)"
  fi

  read -rp "Gửi về Telegram? (y/n): " send_tele || true

  install_deps
  add_user "$username" "$password"
  write_squid_conf "$port"
  restart_squid

  ip="$(get_public_ip)"
  echo "===================================="
  echo " ✅ Proxy đã tạo thành công"
  echo "    Định dạng: ${ip:-IP_UNKNOWN}:$port:$username:$password"
  echo "===================================="

  if [[ "${send_tele:-n}" =~ ^[yY]$ ]]; then
    send_telegram "✅ Proxy mới:
${ip:-IP_UNKNOWN}:$port:$username:$password"
  fi
}

noninteractive_install() {
  local username password port send_tele ip
  username="${USER_ARG:-kingproxy}"
  password="${PASS_ARG:-kingproxy}"
  port="${PORT_ARG:-$(random_port)}"
  send_tele="${SEND_TELE:-n}"

  install_deps
  add_user "$username" "$password"
  write_squid_conf "$port"
  restart_squid

  ip="$(get_public_ip)"
  echo "===================================="
  echo " ✅ Proxy đã tạo thành công"
  echo "    Định dạng: ${ip:-IP_UNKNOWN}:$port:$username:$password"
  echo "===================================="

  if [[ "${send_tele}" =~ ^[yY]$ ]]; then
    send_telegram "✅ Proxy mới:
${ip:-IP_UNKNOWN}:$port:$username:$password"
  fi
}

do_adduser() {
  need_root
  install_deps
  local username password
  username="${USER_ARG:-}"
  password="${PASS_ARG:-}"

  if [[ -z "$username" ]]; then
    read -rp "Nhập username: " username
  fi
  if [[ -z "$password" ]]; then
    read -rp "Nhập password: " password
  fi

  add_user "$username" "$password"
  restart_squid
  log "✅ Added/updated user: $username"
}

main() {
  case "${CMD:-}" in
    install|"")
      need_root
      if [[ -n "$USER_ARG" || -n "$PASS_ARG" || -n "$PORT_ARG" || -n "$SEND_TELE" ]]; then
        noninteractive_install
      else
        interactive_install
      fi
      ;;
    adduser)
      do_adduser
      ;;
    show)
      show_info
      ;;
    uninstall)
      need_root
      uninstall_all
      ;;
    update)
      self_update
      ;;
    *)
      usage
      die "Command không hợp lệ: ${CMD:-"(rỗng)"}"
      ;;
  esac
}

main
