#!/usr/bin/env bash
set -Eeuo pipefail

# =========================
#  createproxy.sh (Improved)
# =========================

# === Telegram Bot Config (chỉ dùng nếu chọn gửi) ===
BOT_TOKEN="$7737030927:AAEmdQNSxxKE7HgnhyOAORuqoRYMFcPnWGc"
CHAT_ID="$6267128183"

# === Default user/pass nếu không nhập ===
DEFAULT_USER="kingproxy"
DEFAULT_PASS="kingproxy"

# === Squid config ===
SQUID_CONF="/etc/squid/squid.conf"
SQUID_PASSWD="/etc/squid/passwd"
SQUID_LOG="/var/log/squid/access.log"

# ===== Helpers =====
RED=$'\e[31m'; GRN=$'\e[32m'; YEL=$'\e[33m'; CYN=$'\e[36m'; RST=$'\e[0m'
log()  { echo "${CYN}[*]${RST} $*"; }
ok()   { echo "${GRN}[✓]${RST} $*"; }
warn() { echo "${YEL}[!]${RST} $*"; }
die()  { echo "${RED}[x]${RST} $*" >&2; exit 1; }

cleanup_on_error() {
  warn "Có lỗi xảy ra. Bạn có thể xem log/systemctl status squid để biết thêm."
}
trap cleanup_on_error ERR

need_root() {
  if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
    die "Vui lòng chạy bằng root: sudo bash createproxy.sh"
  fi
}

have_cmd() { command -v "$1" >/dev/null 2>&1; }

detect_pkg_mgr() {
  if have_cmd apt-get; then
    echo "apt"
  elif have_cmd yum; then
    echo "yum"
  elif have_cmd dnf; then
    echo "dnf"
  else
    echo ""
  fi
}

install_packages() {
  local pmgr
  pmgr="$(detect_pkg_mgr)"
  [[ -n "$pmgr" ]] || die "Không tìm thấy trình quản lý gói (apt/yum/dnf)."

  log "Cài đặt gói cần thiết: squid + apache2-utils + curl"
  if [[ "$pmgr" == "apt" ]]; then
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -y
    apt-get install -y squid apache2-utils curl
  elif [[ "$pmgr" == "yum" ]]; then
    yum install -y squid httpd-tools curl
  elif [[ "$pmgr" == "dnf" ]]; then
    dnf install -y squid httpd-tools curl
  fi
  ok "Cài đặt xong"
}

find_basic_auth_bin() {
  # các đường dẫn phổ biến
  local candidates=(
    "/usr/lib/squid/basic_ncsa_auth"
    "/usr/lib64/squid/basic_ncsa_auth"
    "/usr/lib/squid3/basic_ncsa_auth"
    "/usr/libexec/squid/basic_ncsa_auth"
    "/usr/libexec/basic_ncsa_auth"
  )
  for p in "${candidates[@]}"; do
    if [[ -x "$p" ]]; then
      echo "$p"
      return 0
    fi
  done

  # fallback: tìm nhanh
  local found
  found="$(find /usr -type f -name basic_ncsa_auth 2>/dev/null | head -n 1 || true)"
  [[ -n "$found" && -x "$found" ]] && { echo "$found"; return 0; }

  return 1
}

random_port() {
  # ưu tiên port ngẫu nhiên nhưng đảm bảo chưa dùng
  local port
  for _ in {1..50}; do
    port=$((RANDOM % 63000 + 2000))
    if ! ss -lnt 2>/dev/null | awk '{print $4}' | grep -q ":$port$"; then
      echo "$port"
      return 0
    fi
  done
  # fallback nếu xui
  echo "3128"
}

get_public_ipv4() {
  # ifconfig.me đôi khi chập chờn -> có fallback
  local ip=""
  ip="$(curl -fsS -4 --max-time 8 ifconfig.me 2>/dev/null || true)"
  if [[ -z "$ip" ]]; then
    ip="$(curl -fsS -4 --max-time 8 api.ipify.org 2>/dev/null || true)"
  fi
  if [[ -z "$ip" ]]; then
    ip="$(curl -fsS -4 --max-time 8 icanhazip.com 2>/dev/null || true)"
  fi
  echo "${ip//[$'\r\n ']/}"
}

backup_conf() {
  if [[ -f "$SQUID_CONF" ]]; then
    cp -a "$SQUID_CONF" "${SQUID_CONF}.bak.$(date +%Y%m%d_%H%M%S)"
    ok "Đã backup squid.conf"
  fi
}

write_squid_conf() {
  local auth_bin="$1"
  local port="$2"

  mkdir -p "$(dirname "$SQUID_PASSWD")"
  mkdir -p "$(dirname "$SQUID_LOG")"

  cat > "$SQUID_CONF" <<EOF
# ===== Auto-generated by createproxy.sh =====
# Basic authentication
auth_param basic program $auth_bin $SQUID_PASSWD
auth_param basic realm ProxyKing
acl authenticated proxy_auth REQUIRED

# Access rules
http_access allow authenticated
http_access deny all

# Listen port
http_port $port

# No caching
cache deny all

# Logging
access_log $SQUID_LOG
EOF

  ok "Đã ghi cấu hình Squid"
}

create_user() {
  local user="$1"
  local pass="$2"

  # -b: batch mode; -c: create file; dùng -c chỉ khi file chưa tồn tại
  if [[ -f "$SQUID_PASSWD" ]]; then
    htpasswd -b "$SQUID_PASSWD" "$user" "$pass" >/dev/null
  else
    htpasswd -bc "$SQUID_PASSWD" "$user" "$pass" >/dev/null
  fi
  ok "Đã tạo user xác thực"
}

restart_squid() {
  # service name có thể là squid hoặc squid3
  if systemctl list-unit-files | grep -q '^squid\.service'; then
    systemctl enable --now squid >/dev/null 2>&1 || true
    systemctl restart squid
    systemctl is-active --quiet squid || die "Squid không chạy (squid)."
  elif systemctl list-unit-files | grep -q '^squid3\.service'; then
    systemctl enable --now squid3 >/dev/null 2>&1 || true
    systemctl restart squid3
    systemctl is-active --quiet squid3 || die "Squid không chạy (squid3)."
  else
    # fallback
    systemctl restart squid 2>/dev/null || systemctl restart squid3 2>/dev/null || die "Không restart được Squid."
  fi
  ok "Squid đã restart"
}

send_telegram() {
  local ip="$1" port="$2" user="$3" pass="$4"

  # nếu user chưa set token/chat id thì bỏ qua để tránh fail
  if [[ "$BOT_TOKEN" == "YOUR_BOT_TOKEN" || "$CHAT_ID" == "YOUR_CHAT_ID" ]]; then
    warn "Bạn chọn gửi Telegram nhưng BOT_TOKEN/CHAT_ID chưa được cấu hình. Bỏ qua."
    return 0
  fi

  local msg
  msg="✅ Proxy mới đã được tạo:
Định dạng: ${ip}:${port}:${user}:${pass}"

  curl -fsS -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
    -d "chat_id=${CHAT_ID}" \
    -d "text=${msg}" >/dev/null || warn "Gửi Telegram thất bại (token/chat id/network)."
  ok "Đã gửi Telegram"
}

# ===== Main =====
need_root
install_packages

# ==== hỏi user/pass ====
read -r -p "Bạn muốn nhập username? (y/n): " choice
if [[ "$choice" =~ ^[yY]$ ]]; then
  read -r -p "Nhập username: " USERNAME
  # random pass 10 ký tự
  PASSWORD="$(tr -dc A-Za-z0-9 </dev/urandom | head -c 10)"
  [[ -n "${USERNAME// }" ]] || die "Username rỗng."
else
  USERNAME="$DEFAULT_USER"
  PASSWORD="$DEFAULT_PASS"
fi

# ==== hỏi gửi telegram ====
read -r -p "Bạn có muốn gửi thông tin proxy về Telegram? (y/n): " send_tele

# ==== chọn port ====
PORT="$(random_port)"

# ==== tìm basic_ncsa_auth ====
AUTH_BIN="$(find_basic_auth_bin || true)"
[[ -n "$AUTH_BIN" ]] || die "Không tìm thấy basic_ncsa_auth. Hãy kiểm tra cài squid đúng chưa."

# ==== tạo user ====
create_user "$USERNAME" "$PASSWORD"

# ==== ghi config ====
backup_conf
write_squid_conf "$AUTH_BIN" "$PORT"
restart_squid

# ==== lấy ip ====
IP="$(get_public_ipv4)"
[[ -n "$IP" ]] || warn "Không lấy được IP công khai IPv4. Bạn có thể tự kiểm tra bằng: curl -4 ifconfig.me"

# ==== in kết quả ====
echo "===================================="
echo " ✅ Proxy đã tạo thành công"
echo "    Định dạng: ${IP:-UNKNOWN_IP}:$PORT:$USERNAME:$PASSWORD"
echo
echo " 🌐 IP: ${IP:-UNKNOWN_IP}"
echo " 🔌 PORT: $PORT"
echo " 👤 USER: $USERNAME"
echo " 🔑 PASS: $PASSWORD"
echo "===================================="

# ==== gửi telegram nếu chọn ====
if [[ "$send_tele" =~ ^[yY]$ ]]; then
  send_telegram "${IP:-UNKNOWN_IP}" "$PORT" "$USERNAME" "$PASSWORD"
fi
