#!/usr/bin/env bash
set -Eeuo pipefail

# =========================
#  CREATE SQUID PROXY (AUTH)
#  - Random port
#  - Optional custom username
#  - Optional Telegram send
#  - Works on Ubuntu/Debian
# =========================

# ---------- Helpers ----------
die() { echo "❌ $*" >&2; exit 1; }
need_root() { [[ "${EUID:-$(id -u)}" -eq 0 ]] || die "Hãy chạy bằng root: sudo bash $0"; }

command_exists() { command -v "$1" >/dev/null 2>&1; }

gen_pass() {
  # 10 ký tự A-Za-z0-9
  tr -dc 'A-Za-z0-9' </dev/urandom | head -c 10
}

get_public_ipv4() {
  # nhiều nguồn fallback
  local ip=""
  for url in "https://ifconfig.me" "https://api.ipify.org" "https://ipv4.icanhazip.com"; do
    ip="$(curl -fsS -4 --max-time 8 "$url" 2>/dev/null | tr -d ' \n\r' || true)"
    [[ "$ip" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] && { echo "$ip"; return 0; }
  done
  echo "UNKNOWN"
}

random_port() {
  # random 2000-65000, cố gắng tránh port đã dùng
  local p
  for _ in {1..50}; do
    p=$((RANDOM % 63000 + 2000))
    if ! ss -lnt 2>/dev/null | awk '{print $4}' | grep -qE ":${p}\$"; then
      echo "$p"
      return 0
    fi
  done
  echo $((RANDOM % 63000 + 2000))
}

# ---------- Main ----------
need_root

echo "===================================="
echo "  🧰 CREATE PROXY (SQUID AUTH)"
echo "===================================="

# Telegram config (optional)
BOT_TOKEN="$7737030927:AAEmdQNSxxKE7HgnhyOAORuqoRYMFcPnWGc"
CHAT_ID="$6267128183"

# Ask user/pass
read -r -p "Bạn muốn nhập username? (y/n): " choice
choice="${choice:-n}"

USERNAME="kingproxy"
PASSWORD="kingproxy"

if [[ "$choice" =~ ^[Yy]$ ]]; then
  read -r -p "Nhập username: " USERNAME
  USERNAME="${USERNAME:-kingproxy}"
  PASSWORD="$(gen_pass)"
fi

read -r -p "Bạn có muốn gửi thông tin proxy về Telegram? (y/n): " send_tele
send_tele="${send_tele:-n}"

# Install packages
export DEBIAN_FRONTEND=noninteractive

echo "🔄 Cài đặt gói cần thiết (squid apache2-utils curl)..."
apt-get update -y
apt-get install -y squid apache2-utils curl >/dev/null

# Create auth file
PASSWD_FILE="/etc/squid/passwd"
mkdir -p /etc/squid

echo "👤 Tạo user xác thực..."
htpasswd -bc "$PASSWD_FILE" "$USERNAME" "$PASSWORD" >/dev/null

# Configure squid
SQUID_CONF="/etc/squid/squid.conf"
BACKUP="/etc/squid/squid.conf.bak.$(date +%Y%m%d_%H%M%S)"

if [[ -f "$SQUID_CONF" ]]; then
  cp -f "$SQUID_CONF" "$BACKUP"
fi

PORT="$(random_port)"

cat > "$SQUID_CONF" <<EOF
# ==== Auto generated by creatproxy.sh ====
auth_param basic program /usr/lib/squid/basic_ncsa_auth $PASSWD_FILE
auth_param basic realm ProxyKing
acl authenticated proxy_auth REQUIRED
http_access allow authenticated

# Listen
http_port $PORT

# Hardening / minimal cache
cache deny all
access_log /var/log/squid/access.log
EOF

echo "🚀 Restart squid..."
systemctl enable squid >/dev/null 2>&1 || true
systemctl restart squid

# Get IP
IP="$(get_public_ipv4)"

echo "===================================="
echo " ✅ Proxy đã tạo thành công"
echo "    Định dạng: $IP:$PORT:$USERNAME:$PASSWORD"
echo "===================================="

# Telegram send
if [[ "$send_tele" =~ ^[Yy]$ ]]; then
  if [[ "$BOT_TOKEN" == "YOUR_BOT_TOKEN" || "$CHAT_ID" == "YOUR_CHAT_ID" ]]; then
    echo "⚠️ Bạn chưa set BOT_TOKEN/CHAT_ID nên bỏ qua gửi Telegram."
  else
    MESSAGE="✅ Proxy mới đã được tạo:
Định dạng: ${IP}:${PORT}:${USERNAME}:${PASSWORD}"
    curl -fsS -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
      -d chat_id="$CHAT_ID" \
      -d text="$MESSAGE" >/dev/null \
      && echo "📩 Đã gửi Telegram." || echo "⚠️ Gửi Telegram thất bại."
  fi
fi
